# =============================================================================
# dbt Profiles - Database connection configuration
# This file tells dbt how to connect to your database
# =============================================================================

weather_transformations:
  target: dev  # Default environment
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres123
      dbname: weather_db
      schema: public
      threads: 4
