# =============================================================================
# Schema definition for mart models
# =============================================================================

version: 2

models:
  - name: weather_summary
    description: "Aggregated weather data with categorizations, ready for dashboards"
    columns:
      - name: city_name
        description: "Name of the city"
        tests:
          - not_null
      - name: temp_celsius
        description: "Temperature in Celsius"
      - name: temp_category
        description: "Temperature category (Freezing, Cold, Mild, Warm, Hot)"
      - name: humidity_category
        description: "Humidity category (Low, Normal, High)"
